spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true

  messages:
    basename: message/applicationMessage
    encoding: UTF-8

  jwt:
    secret: govlepel@$&